name: CI/CD Pipeline for C# Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 

      - name: Restore dependencies
        run: dotnet restore WebTV/WebTV.csproj

      - name: Build project
        run: dotnet build WebTV/WebTV.csproj --configuration Release

      - name: Run tests
        run: dotnet test WebTV/WebTV.csproj --configuration Release --no-build

      - name: Publish project
        run: dotnet publish WebTV/WebTV.csproj --configuration Release --output ./publish

      - name: Build Docker image
        run: docker build -t webtv ./publish

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and Push Docker image to ECR
        run: |
          docker tag webtv:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/webtv:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/webtv:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Cài đặt unzip nếu chưa có
            if ! command -v unzip &> /dev/null; then
              sudo apt update
              sudo apt install -y unzip
            fi

            # Cài đặt AWS CLI nếu chưa có
            if ! command -v aws &> /dev/null; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              rm -rf awscliv2.zip aws
            fi

            # Cài đặt Docker nếu chưa có
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            fi

            # Đặt AWS credentials từ GitHub Secrets
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION="ap-southeast-2"

            # Đăng nhập vào ECR
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com

            # Tải image mới nhất từ ECR
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/webtv:latest

            # Dừng và xóa container cũ nếu tồn tại
            docker stop webtv || true
            docker rm webtv || true

            # Chạy container mới
            docker run -d --name webtv -p 5001:5001 \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/webtv:latest
